trigger:
  branches:
    include:
      - develop
      - feature/**
      - release/**
      - master
      - hotfix/**

pr:
  branches:
    include:
      - develop
      - master

pool:
  name: Default # Use self-host agent pool named 'Default'

resources:
  - repo: self

variables:
  buildConfiguration: Release 
  packageJsonPath: $(Build.SourcesDirectory)/package.json

stages:
  - stage: BuildStage
    displayName: Build
    jobs:
      - job: BuildJob
        displayName: Build
        steps:
          - task: PowerShell@2
            displayName: Build
            inputs:
              targetType: inline
              script: |
                pnpm i  
                pnpm run lint 
                pnpm run build
      
  - stage: TestStage 
    displayName: Test 
    dependsOn: BuildStage
    jobs:
      - job: UnitTestsJob
        displayName: Run Unit Tests 
        steps:
          - task: PowerShell@2
            displayName: Run Unit Tests
            inputs:
              targetType: inline
              script: |
                pnpm run test          

  - stage: PublishStage
    displayName: Publish
    dependsOn: TestStage
    jobs:
      - job: PublishJob
        displayName:  Publish Artifacts
        steps:
          - task: PowerShell@2
            displayName: Generate Version
            inputs:
              targetType: inline
              script: |
                $version = & $(Build.SourcesDirectory)/scripts/GenerateBuildVersion.ps1 -Revision $(Build.BuildId)
                Write-Host "##vso[task.setvariable variable=BuildVersion]$version"

          - task: PowerShell@2
            displayName: Update Version
            inputs:
              targetType: inline
              script: |
                $packageJson = Get-Content $(packageJsonPath) -Raw | ConvertFrom-Json
                $packageJson.version = "$(BuildVersion)"
                $packageJson | ConvertTo-Json -Depth 32 | Set-Content $(packageJsonPath)
                  
          - task: PowerShell@2
            displayName: Publish Artifacts
            inputs:
              targetType: inline
              script: |
                pnpm run build

          - task: PublishPipelineArtifact@1
            displayName: Publish RichillCapital.SharedKernel Artifacts
            inputs:
              targetPath: $(artifactsPath)
              artifact: RichillCapital.SharedKernel-$(buildConfiguration)-$(BuildVersion)
              publishLocation: pipeline                


#   - stage: ReleaseStage
#     displayName: Build release artifacts 
#     dependsOn: BuildStage
#     condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')

#     jobs:
#       - job: ReleaseJob
#         displayName: Build release artifacts
#         steps:
#           - task: PowerShell@2
#             displayName: Generate release version
#             inputs:
#               targetType: inline
#               script: |
#                 Write-Host "Generating release version from branch: $(Build.SourceBranch)"

#                 $branchName = "$(Build.SourceBranchName)"
#                 Write-Host "##vso[task.setvariable variable=ReleaseVersion]$branchName"

#                 Write-Host "Generated Release Version: $branchName"

#           - task: PowerShell@2
#             displayName: Update package.json version
#             inputs:
#               targetType: inline
#               script: |
#                 Write-Host "Updating package.json version..."

#                 $packageJsonPath = "$(System.DefaultWorkingDirectory)/package.json"
#                 $packageJson = Get-Content $packageJsonPath -Raw | ConvertFrom-Json
#                 $packageJson.version = "$(ReleaseVersion)"
#                 $packageJson | ConvertTo-Json -Depth 32 | Set-Content $packageJsonPath

#                 Write-Host "Updated package.json version to $(ReleaseVersion)"

#           - script: pnpm i  
#             displayName: Install dependencies 

#           - script: pnpm run build  
#             displayName: Generate release build 

#           - task: PublishPipelineArtifact@1
#             displayName: Publish pipeline artifact
#             inputs:
#               targetPath: $(Build.SourcesDirectory)/artifacts
#               artifact: 'RichillCapital.SharedKernel-$(ReleaseVersion)'
#               publishLocation: 'pipeline'             

#   - stage: ProductionStage
#     displayName: Production deployment
#     dependsOn: BuildStage
#     condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

#     jobs:
#       - job: DeployProductionJob
#         displayName: Publish to NPM registry
#         steps:
#           - task: PowerShell@2
#             displayName: Generate release version from latest release branch
#             inputs:
#               targetType: inline
#               script: |
#                 git fetch --all

#                 $branches = git branch -r | Where-Object { $_ -match 'origin/release/\d+\.\d+\.\d+' }

#                 if (-not $branches) {
#                     Write-Error "No matching branches found."
#                     exit 1
#                 }

#                 $versions = $branches |
#                 ForEach-Object {
#                     if ($_ -match 'origin/release/(\d+\.\d+\.\d+)') {
#                         [PSCustomObject]@{
#                             BranchName = $_.Trim()
#                             Version = [System.Version]$matches[1]
#                         }
#                     }
#                 }

#                 $latestBranch = $versions |
#                     Sort-Object -Property Version -Descending |
#                     Select-Object -First 1

#                 if ($latestBranch) {
#                     Write-Host "##vso[task.setvariable variable=ReleaseVersion]$($latestBranch.Version)"
#                     Write-Host "Generated release version: $($latestBranch.Version)"
#                 } else {
#                     Write-Error "Failed to find the latest release branch."
#                     exit 1
#                 }

#           - task: PowerShell@2
#             displayName: Update package.json version
#             inputs:
#               targetType: inline
#               script: |
#                 Write-Host "Updating package.json version..."

#                 $packageJsonPath = "$(System.DefaultWorkingDirectory)/package.json"
#                 $packageJson = Get-Content $packageJsonPath -Raw | ConvertFrom-Json
#                 $packageJson.version = "$(ReleaseVersion)"
#                 $packageJson | ConvertTo-Json -Depth 32 | Set-Content $packageJsonPath

#                 Write-Host "Updated package.json version to $(ReleaseVersion)"

#           - script: pnpm i  
#             displayName: Install dependencies 

#           - script: pnpm run build  
#             displayName: Generate release build 
            
#           - task: PowerShell@2
#             displayName: Create and push git tag
#             inputs:
#               targetType: inline
#               script: |
#                 git config user.name "Mengsyue Amao Tsai"
#                 git config user.email "mengsyue.tsai@outlook.com"
#                 git fetch --tags

#                 $tagName = "v$(ReleaseVersion)"
#                 $existingTags = git tag --list
#                 if ($existingTags -contains $tagName) {
#                   Write-Host "Tag $tagName already exists."
#                   exit 0
#                 }                

#                 git tag -a "v$(ReleaseVersion)" -m "Release version $(ReleaseVersion)"
#                 git push origin "v$(ReleaseVersion)"

#           - task: PowerShell@2
#             displayName: Write authentication token to .npmrc
#             inputs:
#               targetType: inline
#               script: |
#                 $token = "$(NPM_TOKEN)"
#                 $auth = "//registry.npmjs.org/:_authToken=$($token)"
#                 $npmrcPath = "$(System.DefaultWorkingDirectory)/.npmrc"
#                 Set-Content -Path $npmrcPath -Value $auth
#                 Write-Host "Authentication token written to .npmrc"
                
#           - script: pnpm publish --access public --no-git-checks || echo "Package already exists, skipping publish"
#             displayName: Publish package to npm registry