trigger:
  branches:
    include:
      - develop
      - feature/**
      - release/**
      - master
      - hotfix/**

pr:
  branches:
    include:
      - develop
      - master

pool:
  name: 'Default' # Use self-host agent pool named 'Default'

variables:
  nodeVersion: '22.x'

resources:
  - repo: self

stages:
  - stage: DevelopmentStage
    displayName: Development stage 

    jobs:
      - job: DevelopmentJob
        displayName: Development job

        steps:
          - script: pnpm i 
            displayName: 'Install dependencies'

          - script: pnpm run lint 
            displayName: 'Lint'

          - script: pnpm run build 
            displayName: 'Build'

          - script: pnpm run test 
            displayName: 'Test'

      - job: PublishJob
        displayName: PublishJob
        dependsOn: DevelopmentJob
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

        steps:
          - task: PowerShell@2
            displayName: Generate build version
            inputs:
              targetType: inline
              script: |
                Write-Host "Generating build version..."

                $buildVersion = (Get-Date).ToString("yy.MMdd") + ".$(Build.BuildId)"
                Write-Host "##vso[task.setvariable variable=BuildVersion]$buildVersion"

                Write-Host "Generated Build Version: $buildVersion"     
          
          - task: PowerShell@2
            displayName: Update package.json version 
            inputs:
              targetType: inline
              script: |
                Write-Host "Updating package.json version..."

                $packageJsonPath = "$(System.DefaultWorkingDirectory)/package.json"
                $packageJson = Get-Content $packageJsonPath -Raw | ConvertFrom-Json
                $packageJson.version = "$(BuildVersion)"
                $packageJson | ConvertTo-Json -Depth 32 | Set-Content $packageJsonPath

                Write-Host "Updated package.json version to $(BuildVersion)"

          - script: pnpm i
            displayName: Install dependencies

          - script: pnpm run build
            displayName: 'Build'

          - task: PublishPipelineArtifact@1
            displayName: Publish pipeline artifact
            inputs:
              targetPath: $(Build.SourcesDirectory)/artifacts
              artifact: 'RichillCapital.SharedKernel-$(BuildVersion)'
              publishLocation: 'pipeline'
